server:
  port: 8080
  servlet:
    context-path: /bookings

spring:
  datasource: 
    url: ${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate: 
        ddl-auto: update
        show-sql: true
  config:
    import: optional:file:.env[.properties]

# Set the swagger ui after adding the dependency
springdoc:
  api-docs:
    enabled: true 
  swagger-ui:
    enabled: true