server:
  port: 8080

spring:
  datasource: 
    url: ${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate: 
        ddl-auto: update
        show-sql: true
  config:
    import: optional:file:.env[.properties]